CREATE DATABASE IF NOT EXISTS kvdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'kvuser'@'%' IDENTIFIED BY 'kvpass';
GRANT ALL PRIVILEGES ON kvdb.* TO 'kvuser'@'%';
FLUSH PRIVILEGES;

USE kvdb;
CREATE TABLE IF NOT EXISTS kv_store (
  `key` VARCHAR(255) NOT NULL PRIMARY KEY,
  `value` MEDIUMTEXT NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

